# Generated by Django 4.0.1 on 2022-01-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustumersSighnUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('emial', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('check1', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
