# Generated by Django 4.0.1 on 2022-01-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
